config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  devise_for :users, :controllers => {
    :registrations => "registrations"
  }
  resources :users, only: [:show, :index, :destroy] do
    member do
      get :friend, :friends_list, :talk
    end
  end
  resources :posts
  resources :recipes, only: [:index]
  resources :others, only: [:index]
  resources :travels, only: [:index]
  resources :lifes, only: [:index]
  resources :learns, only: [:index]
  resources :healths, only: [:index]
  resources :cooks, only: [:index]
  resources :goes, only: [:index]
  resources :ingredients, only: [:index, :create, :destroy]
  resources :surveys, only: [:create]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :friends, only: [:create, :destroy]
  resources :talks, only: [:create, :destroy]

  

end

app/models/comment.rb
class Comment < ApplicationRecord
    
    belongs_to :user
    belongs_to :post
    
    validates :post_id, presence: true
    validates :user_id, presence: true
    validates :content, presence: true
    
end

app/models/friend.rb
class Friend < ApplicationRecord
    
    belongs_to :user, class_name: 'User', foreign_key: 'user_id'
    belongs_to :rq, class_name: 'User', foreign_key: "user_id_rq"
    
    validates :user_id, presence: true
    validates :user_id_rq, presence: true
     
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    
    belongs_to :user
    belongs_to :recipe
    
end

app/models/like.rb
class Like < ApplicationRecord
    
    belongs_to :user
    belongs_to :post
    
    validates :post_id, presence: true
    validates :user_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    
    belongs_to :user
    has_many :post_details, dependent: :destroy
    
    has_many :users, through: :likes
    has_many :likes, dependent: :delete_all
    
    has_many :users, through: :comments
    has_many :comments, dependent: :delete_all
    
    accepts_nested_attributes_for :post_details, allow_destroy: true
    default_scope -> { order('created_at DESC') }
    
    validates :user_id, presence: true
    validates :category, presence: true
    validates :title, presence: true
    validates :main_content, presence: true
    
end

app/models/post_detail.rb
class PostDetail < ApplicationRecord
    
    belongs_to :post
    default_scope -> { order('created_at ASC') }
    
    mount_uploader :image, ImageUploader
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    
    has_many :users, through: :ingredients
    has_many :ingredients
    
end

app/models/sentence.rb
class Sentence < ApplicationRecord
end

app/models/survey.rb
class Survey < ApplicationRecord
    belongs_to :user
    
    validates :user_id, presence: true
    validates :category, presence: true

end

app/models/talk.rb
class Talk < ApplicationRecord
    belongs_to :written_user, class_name: 'User', foreign_key: 'written_user_id'
    belongs_to :receiver_user, class_name: 'User', foreign_key: 'receiver_user_id'
    
    validates :written_user, presence: true
    validates :receiver_user, presence: true
    validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
    
    mount_uploader :image, ImageUploader
    
    validates :name, presence: true, length: { maximum: 50 }
    
    has_many :recipes, through: :ingredients
    has_many :ingredients, dependent: :destroy
    
    has_many :posts, through: :likes
    has_many :likes, dependent: :delete_all
    
    has_many :posts, through: :comments
    has_many :comments, dependent: :delete_all
    
    has_many :friends_of_user, class_name: 'Friend', foreign_key: 'user_id',dependent: :delete_all
    has_many :friends_of_user_id_rq, class_name: 'Friend', foreign_key: 'user_id_rq',dependent: :delete_all
    has_many :user_id, through: :friends_of_user
    has_many :user_id_rq, through: :friends_of_user_id_rq
    
    has_many :talks_of_written_user, class_name: 'Talk', foreign_key: 'written_user_id',dependent: :destroy
    has_many :talks_of_receiver_user, class_name: 'Talk', foreign_key: 'receiver_user_id',dependent: :destroy
    has_many :written_user_id, through: :talks_of_written_user
    has_many :receiver_user_id, through: :talks_of_receiver_user
    
    
    has_many :surveys, dependent: :destroy
    
    has_many :posts, dependent: :destroy
    
    scope :get_by_name, ->(name) {
    where("name like ?" , "%#{name}%")
    }
    
    def like?(post)
        likes.find_by(post_id: post.id)
    end
    
    def accept?(user)
       friends_of_user.find_by(user_id_rq: user.id) && friends_of_user_id_rq.find_by(user_id: user.id)
    end
    
    def friend_request?(user)
       friends_of_user.find_by(user_id_rq: user.id)
    end
    
    def wait?(user)
      friends_of_user_id_rq.find_by(user_id: user.id)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: :destroy
  
  def index
    @users = User.paginate(page: params[:page], per_page: 15)
    if params[:name].present?
      @users = @users.get_by_name params[:name]
    end
  end
    
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
    @comments = @user.comments.paginate(page: params[:page])
    @likes = @user.likes.paginate(page: params[:page])
    @like = Like.new
    @talk = Talk.new
    @ingredients = @user.ingredients.where(recipe_id: 1..64).order(:check_box)
    @friend = current_user.friends_of_user.new
    @friends = []
    @request_friends = []
    @receive_friends = []
    @friend_status = ""
    
    Friend.where(user_id: current_user.id).each do |f|
      if Friend.find_by('user_id = ? and user_id_rq = ?', f.user_id_rq, current_user.id) 
        @friends.push(f.user_id_rq)
        @friend_status = "f"
      else
        @request_friends.push(f.user_id_rq)
        @friend_status = "r"
      end
    end
    
    Friend.where(user_id_rq: current_user.id).each do |f|
      if !Friend.find_by('user_id = ? and user_id_rq = ?', current_user.id, f.user_id) 
      logger.debug("--------------------- 承認待ち　f.user_id_rq = #{f.user_id}")
        	@receive_friends.push(f.user_id)
    	    @friend_status = "w"
      end
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end
  
  def friend
    @user = User.find(params[:id])
    @friend = current_user.friends_of_user.new
  end 
  
  def friends_list
    @friend = current_user.friends_of_user.new
    @friends = []
    @request_friends = []
    @receive_friends = []
    @friend_status = ""
    
    Friend.where(user_id: current_user.id).each do |f|
      if Friend.find_by('user_id = ? and user_id_rq = ?', f.user_id_rq, current_user.id) 
        @friends.push(f.user_id_rq)
        @friend_status = "f"
      else
        @request_friends.push(f.user_id_rq)
        @friend_status = "r"
      end
    end
    
    Friend.where(user_id_rq: current_user.id).each do |f|
      if !Friend.find_by('user_id = ? and user_id_rq = ?', current_user.id, f.user_id) 
      logger.debug("--------------------- 承認待ち　f.user_id_rq = #{f.user_id}")
        	@receive_friends.push(f.user_id)
    	    @friend_status = "w"
      end
    end
  end
  
  def talk
    @user = User.find(params[:id])
    @talk = Talk.new
    @all = Talk.where("(written_user_id = ?) OR (written_user_id = ?)",current_user.id, @user.id)
    @talks = @all.where("(receiver_user_id = ?) OR (receiver_user_id = ?)",current_user.id, @user.id)
  end
  
  private
  
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
  
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/goes_helper.rb
module GoesHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/helpers/lifes_helper.rb
module LifesHelper
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_comment.html.erb
<li>
    <% post = Post.find_by(id: comment.post_id) %>
    <%= image_tag 'post/comment.png', class: 'show-like-img' %>
    <span>■ <%= link_to post.title, post_path(post)  %></span></br>
    <span>☆ <%= comment.content %></span>
</li>

app/views/users/_friend.html.erb
<li class="friend">
    <% user = User.find_by(id: friend) %>
        <% if user.image? %>
            <%= image_tag user.image.thumb.url %>
        <% else %>
            <%= image_tag 'user/user-face.png', class: 'index-user-face-img' %>
        <% end %>
    <%= link_to user.name, user_path(user) %>
</li>

app/views/users/_like.html.erb
<li class="break">
    <% post = Post.find_by(id: like.post_id) %>
    <%= image_tag 'post/like.png', class: 'show-like-img' %>
    ■ <%= link_to post.title, post_path(post) %>
</li>

app/views/users/_receive_friend.html.erb
<li class="request_friend">
    <% user = User.find_by(id: receive_friend) %>
        <% if user.image? %>
            <%= image_tag user.image.thumb.url %>
        <% else %>
            <%= image_tag 'user/user-face.png', class: 'index-user-face-img' %>
        <% end %>
    <%= link_to user.name, user_path(user) %>
</li>

app/views/users/_request_friend.html.erb
<li class="request_friend">
    <% user = User.find_by(id: request_friend) %>
    <% if user.image.present? %>
        <%= image_tag user.image.thumb.url %>
    <% else %>
        <%= image_tag 'user/user-face.png', class: 'index-user-face-img' %>
    <% end %>
    <%= link_to user.name, user_path(user) %>
</li>

app/views/users/_shopping.html.erb
<% if @user.ingredients.any? %>
    <p>■ ■ ■ つくおきレシピ ① ■ ■ ■ </p>
    <ul class="post-index">
        <% @ingredients.each do |ingredient| %>
            <% recipe = Recipe.find(ingredient.recipe_id) %>
            <li>
                <% if ingredient.check_box == 1 %>
                <span><%= recipe.ingredient %></span>　
                <% if recipe.amount.present? %><%= recipe.amount %><% end %>　
                <% if recipe.prepare.present? %><%= image_tag 'shared-menu/star.png', class: 'star-img' %><%= recipe.prepare %></span><% end %>
                <% if recipe.breakdown.present? %><%= recipe.breakdown %></span><% end %>
                <% else %>
                <input type="checkbox" style="width:20px">
                <span class="ingredient-left"><%= recipe.ingredient %></span>　
                <% if recipe.amount.present? %><%= recipe.amount %><% end %>　
                <% if recipe.prepare.present? %><span class="ingredient-right"><%= image_tag 'shared-menu/star.png', class: 'star-img' %><%= recipe.prepare %></span><% end %>
                <% if recipe.breakdown.present? %><span class="ingredient-center"><%= recipe.breakdown %></span><% end %>
                <% end %>
            </li>
        <% end %>
    </ul>
     <%= link_to "delete", ingredient_path, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-lg submit" %>
<% end %>

app/views/users/_talk.html.erb
<li class="talk-box" id="talk <%= talk.id %>">
    <% user = User.find(talk.written_user_id) %>
    <% if talk.written_user_id == current_user.id %>
        <div class="row">
            <span class="timestamp">Writtend <%= time_ago_in_words(talk.created_at) %> ago</span></br>
            <div class="col-sm-10 text-left talk-fram-user">
            <%= talk.message %>
            </div>
            <div class="col-sm-2 talk-face text-center">
                <% if current_user.image? %>
                    <%= image_tag current_user.image.thumb.url, class: 'talk-user-face-img' %>
                <% else %>
                    <%= image_tag 'user/user-face.png', class: 'talk-user-face-img' %>
                <% end %>
                </br><%= user.name %>
            </div>
        </div>
    <% else %>
        <div class="row ">
            <div class="col-sm-2 text-center">
                <% if @user.image? %>
                    <%= image_tag @user.image.thumb.url, class: 'talk-user-face-img' %>
                <% else %>
                    <%= image_tag 'user/user-face.png', class: 'talk-user-face-img' %>
                <% end %>
                </br><%= user.name %>
            </div>
            <div class="col-sm-10 text-left talk-fram">
                <%= talk.message %>
            </div>
            <span class="timestamp">Writtend <%= time_ago_in_words(talk.created_at) %> ago</span>
        </div>
    <% end %>
</li>

app/views/users/_user.html.erb
<li>
    <div class="row">
        <div class="col-md-1 user-index">
            <% if user.image? %>
                <%= image_tag user.image.thumb.url %>
            <% else %>
                <%= image_tag 'user/user-face.png', class: 'index-user-face-img' %>
            <% end %>
        </div>
        <div class="col-md-3 text">
            </br><%= link_to user.name, user %>
            <% if current_user.admin? && !(current_user == user) %>
             | <%= link_to "delete", user, method: :delete, data: {confirm: "You sure?"} %> |
             <% end %>
        </div>
        <div class="col-md-8">
             </br><%= truncate(user.message, length:80) %>
        </div>
    </div>
</li>

app/views/users/friend.html.erb
<% provide(:title, 'friendリクエスト') %>
<%= image_tag 'user/user-line.png', class: 'user-line-img' %>
<div class="container">
  <h2 class="title">Friend Request</h2>
  
  <%= form_for @friend do |f| %>
    <%= f.hidden_field :user_id_rq, :value => @user.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= render 'shared/error_messages', object: f.object %>
        
        <div class="field">
          <%= f.label :message, class: "control-label" %>
          <%= f.text_area :message, autofocus: true, class: "form-control" %>
        </div>
        
      </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <div class="actions">
              <%= f.submit "友達リクエストを送る", class: "btn btn-lg submit" %>
            </div>
        </div>
    </div>
  <% end %>
</div>

app/views/users/friends_list.html.erb
<% provide(:title, 'friends_list') %>
<%= image_tag 'user/user-line.png', class: 'user-line-img' %>
<div class="container">
    <p class="title">Friends List</p>
    <% if @receive_friends.present? %>
        <a href="#receive_friend" class="friends-tag">■ Friendリクエストが届きました！<%= @receive_friends.count %></a>
    <% end %>
    <% if @request_friends.any? %>
        <a href="#request_friends" class="friends-tag">■ Friendリクエスト中！<%= @request_friends.count %></a>
    <% end %>
    <% if @friends.any? %>
        <div class="row friends-list list-border">
            <P>■ Frinds <span class="count"><%= @friends.count %></span></P>
            <div class="col-sm-2">
                <%= image_tag 'user/friend.png', class: 'status-img' %>
            </div>
            <div class="col-sm-10">
                <ul>
                    <%= render partial: 'users/list/friend', collection: @friends %>
                </ul>
            </div>
        </div>
    <% end %>
    <% if @receive_friends.present? %>
        <div class="row friends-list list-border" id="receive_friend">
            <p>■ Friendリクエストが届きました！　<span class="count"><%= @receive_friends.count %></span></p>
            <div class="col-sm-2">
                <%= image_tag 'user/receive.png', class: 'receive-status-img' %>
            </div>
            <div class="col-sm-10">
                <ul>
                    <%= render partial: 'users/list/receive_friend', collection: @receive_friends %>
                </ul>
            </div>
        </div>
    <% end %>
    <% if @request_friends.any? %>
        <div class="row friends-list" id="request_friends">
            <p>■ Friendリクエスト中！　<span class="count"><%= @request_friends.count %></span></p>
            <div class="col-sm-2">
                <%= image_tag 'user/request.png', class: 'request-status-img' %>
            </div>
            <div class="col-sm-10">
                <ul>
                    <%= render partial: 'users/list/request_friend', collection: @request_friends %>
                </ul>
            </div>
        </div>
    <% end %>
</div>  
  

app/views/users/index.html.erb
<% provide(:title, 'Member list') %>
<%= image_tag 'user/user-line.png', class: 'user-line-img' %>
<div class="container">
    <h1 class="title">Members list</h1>
    <div class="surch">
        <%= form_tag(users_path, method: "get") do |f| %>
                <div class="surch-submit">
                    <input type="submit" value="search">
                </div>
                <input type="text" name="name">
        <% end %>
        <div class="clear"></div>
    </div>

    <%= will_paginate renderer: BootstrapPagination::Rails %>
    
    <ul class="users">
        <%= render @users %>
    </ul>
    
    <%= will_paginate renderer: BootstrapPagination::Rails %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%= image_tag 'user/user-line.png', class: 'user-line-img' %>
<div class="container">
    <div class="row">
        <div class="col-sm-12 user-message">
            <p><%= @user.message %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 text-center">
            <% if @user.image? %>
                <%= image_tag @user.image.post.url, class: 'show-user-face-img' %>
            <% else %>
                <%= image_tag 'user/user-face.png', class: 'show-user-face-img' %>
            <% end %>
            <p><%= @user.name %> さん</p>
            <% if current_user == @user %>
                <%= link_to "編集", edit_user_registration_path %>
            <% elsif current_user.accept?(@user) %>
                <p>☆ 友達 ☆</p>
            <% elsif current_user.friend_request?(@user) %>
                <p>友達リクエスト中！</p>
            <% elsif current_user.wait?(@user) %>
                <p>友達リクエストが届いてるよ！</p>
            <%else %>
                <%= link_to "Friendリクエストを送る", friend_user_path %>
            <% end %>
        </div>
        <div class="col-sm-8 friends-box">
            <% if current_user == @user %>
                <% if @friends.present? %>
                    <p><%= link_to "■ Frinds", friends_list_user_path(@user) %> <span class="count"><%= @friends.count %></span></p>
                    <% @accepts = @friends.take(5) %>
                    <ul>
                        <%= render partial: 'users/friend', collection: @accepts %>
                    </ul>
                <% end %>
                <% if @receive_friends.present? %>
                    <p><%= link_to "■ Friendリクエストが届きました！", friends_list_user_path(@user) %> <span class="count"><%= @receive_friends.count %></span></p>
                    <% @receive = @receive_friends.take(5) %>
                    <ul>
                        <%= render partial: 'users/receive_friend', collection: @receive %>
                    </ul>
                <% end %>
                <% if @request_friends.present? %>
                    <p><%= link_to "■ Friendリクエスト中！", friends_list_user_path(@user) %> <span class="count"><%= @request_friends.count %></span></p>
                    <% @request = @request_friends.take(5) %>
                    <ul>
                        <%= render partial: 'users/request_friend', collection: @request %>
                    </ul>
                <% end %>
                <p><a href ="mailto:""">■ 友達を招待する</a></p>
            <% elsif current_user.accept?(@user) %>
            <p>☆<%= @user.name%>さんとお話をしよう！聞きたいことなどあればメッセージを書いて送ってね<p>
                <%= form_for @talk do |f| %>
                    <%= f.hidden_field :receiver_user_id, :value => @user.id %>
                    <%= f.hidden_field :written_user_id, :value => current_user.id %>
                    <%= render 'shared/error_messages', object: f.object %>
                    <div class="field">
                        <%= f.text_area :message, autofocus: true, placeholder: "message....", class: "form-control" %>
                    </div>
                    <div class="row">
                        <div class="talk col-sm-5">
                            <%= f.submit "メッセージを送る", class: "btn btn-lg submit" %>
                        </div>
                    </div>
                          
                <% end %>
                <p>☆Talk Roomで今までの会話が見れるよ</p>
                <div class="row">
                        <div class="col-sm-5">
                           <%= link_to 'Talk Room', talk_user_path, class: "btn btn-lg talk-btn" %>
                        </div>
                    </div>
                    
                
            <% end %>
            
        </div>
    </div>
    <div class="row">
        <section class="py-5">
          <ul class="nav nav-pills nav-fill">
            <li class="nav-item"><a href="#posts" class="nav-link active" data-toggle="tab">投稿　<span class="count"><%= @user.posts.count %></span></a></li>
            <li class="nav-item"><a href="#likes" class="nav-link" data-toggle="tab">お気に入り　<span class="count"><%= @user.likes.count %></span></a></li>
            <li class="nav-item"><a href="#comments" class="nav-link" data-toggle="tab">コメント　<span class="count"><%= @user.comments.count %></span></a></li>
            <li class="nav-item"><a href="#ingredients" class="nav-link" data-toggle="tab">買い物リスト</a></li>
          </ul>
          <div class="tab-content">
            <div id="posts" class="tab-pane active">
                <% if @user.posts.any? %>
                    <ul class="post-index">
                        <%= render partial: 'posts/post', collection: @posts %>
                    </ul>
                <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
                <% end %>
            </div>
            <div id="likes" class="tab-pane">
                <% if @user.likes.any? %>
                    <ul class="post-index">
                        <%= render partial: 'users/like', collection: @likes %>
                    </ul>
                <% end %>
                <%= will_paginate @likes, renderer: BootstrapPagination::Rails %>
            </div>
            <div id="comments" class="tab-pane">
                <% if @user.comments.any? %>
                    <ul class="post-index">
                        <%= render partial: 'users/comment', collection: @comments %>
                    </ul>
                <% end %>
                <%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
            </div>
            <div id="ingredients" class="tab-pane">
                <%= render 'users/shopping' %>
            </div>
          </div>
      </section>
    </div>
</div>

app/views/users/talk.html.erb
<% provide(:title, 'talk room') %>
<%= image_tag 'user/user-line.png', class: 'user-line-img' %>
<div class="container">
    <div class="row talk">
        <p class="title" class: "btn talk-submit">Talk Room</p>
        <a href="#message" class="btn to-message">messageを記入</a>
        <ul>
            <%= render partial: 'users/talk', collection: @talks %>
        </ul>
            
        
        <%= form_for @talk do |f| %>
            <%= f.hidden_field :receiver_user_id, :value => @user.id %>
            <%= f.hidden_field :written_user_id, :value => current_user.id %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="field">
                <%= f.label :message, class: "control-label" %>
                <%= f.text_area :message, autofocus: true, class: "form-control" %>
            </div>
            <div class="col-md-3 col-md-offset-9" id="message">
            <%= f.submit "メッセージを送る", class: "btn talk-submit" %>
            </div>
        <% end %>
    </div>
</div>