config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  devise_for :users, :controllers => {
    :registrations => "registrations"
  }
  resources :users, only: [:show, :index, :destroy] do
    member do
      get :friend, :friends_list, :talk
    end
  end
  resources :posts
  resources :recipes, only: [:index]
  resources :others, only: [:index]
  resources :travels, only: [:index]
  resources :lifes, only: [:index]
  resources :learns, only: [:index]
  resources :healths, only: [:index]
  resources :cooks, only: [:index]
  resources :goes, only: [:index]
  resources :ingredients, only: [:index, :create, :destroy]
  resources :surveys, only: [:create]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :friends, only: [:create, :destroy]
  resources :talks, only: [:create, :destroy]

  

end

app/models/comment.rb
class Comment < ApplicationRecord
    
    belongs_to :user
    belongs_to :post
    
    validates :post_id, presence: true
    validates :user_id, presence: true
    validates :content, presence: true
    
end

app/models/friend.rb
class Friend < ApplicationRecord
    
    belongs_to :user, class_name: 'User', foreign_key: 'user_id'
    belongs_to :rq, class_name: 'User', foreign_key: "user_id_rq"
    
    validates :user_id, presence: true
    validates :user_id_rq, presence: true
     
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    
    belongs_to :user
    belongs_to :recipe
    
end

app/models/like.rb
class Like < ApplicationRecord
    
    belongs_to :user
    belongs_to :post
    
    validates :post_id, presence: true
    validates :user_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    
    belongs_to :user
    has_many :post_details, dependent: :destroy
    
    has_many :users, through: :likes
    has_many :likes, dependent: :delete_all
    
    has_many :users, through: :comments
    has_many :comments, dependent: :delete_all
    
    accepts_nested_attributes_for :post_details, allow_destroy: true
    default_scope -> { order('created_at DESC') }
    
    validates :user_id, presence: true
    validates :category, presence: true
    validates :title, presence: true
    validates :main_content, presence: true
    
end

app/models/post_detail.rb
class PostDetail < ApplicationRecord
    
    belongs_to :post
    default_scope -> { order('created_at ASC') }
    
    mount_uploader :image, ImageUploader
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    
    has_many :users, through: :ingredients
    has_many :ingredients
    
end

app/models/sentence.rb
class Sentence < ApplicationRecord
end

app/models/survey.rb
class Survey < ApplicationRecord
    belongs_to :user
    
    validates :user_id, presence: true
    validates :category, presence: true

end

app/models/talk.rb
class Talk < ApplicationRecord
    belongs_to :written_user, class_name: 'User', foreign_key: 'written_user_id'
    belongs_to :receiver_user, class_name: 'User', foreign_key: 'receiver_user_id'
    
    validates :written_user, presence: true
    validates :receiver_user, presence: true
    validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
    
    mount_uploader :image, ImageUploader
    
    validates :name, presence: true, length: { maximum: 50 }
    
    has_many :recipes, through: :ingredients
    has_many :ingredients, dependent: :destroy
    
    has_many :posts, through: :likes
    has_many :likes, dependent: :delete_all
    
    has_many :posts, through: :comments
    has_many :comments, dependent: :delete_all
    
    has_many :friends_of_user, class_name: 'Friend', foreign_key: 'user_id',dependent: :delete_all
    has_many :friends_of_user_id_rq, class_name: 'Friend', foreign_key: 'user_id_rq',dependent: :delete_all
    has_many :user_id, through: :friends_of_user
    has_many :user_id_rq, through: :friends_of_user_id_rq
    
    has_many :talks_of_written_user, class_name: 'Talk', foreign_key: 'written_user_id',dependent: :destroy
    has_many :talks_of_receiver_user, class_name: 'Talk', foreign_key: 'receiver_user_id',dependent: :destroy
    has_many :written_user_id, through: :talks_of_written_user
    has_many :receiver_user_id, through: :talks_of_receiver_user
    
    
    has_many :surveys, dependent: :destroy
    
    has_many :posts, dependent: :destroy
    
    scope :get_by_name, ->(name) {
    where("name like ?" , "%#{name}%")
    }
    
    def like?(post)
        likes.find_by(post_id: post.id)
    end
    
    def accept?(user)
       friends_of_user.find_by(user_id_rq: user.id) && friends_of_user_id_rq.find_by(user_id: user.id)
    end
    
    def friend_request?(user)
       friends_of_user.find_by(user_id_rq: user.id)
    end
    
    def wait?(user)
      friends_of_user_id_rq.find_by(user_id: user.id)
    end
    
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @ingredient = Ingredient.new
    @recipes = Recipe.where(menu_title: "2018年11月1週目")
  end
  
  def create
    params[:ingredient].each do |ingredient|
      logger.debug("--------------------- 友達　#{ingredient}")
      current_user.ingredients.create!(recipe_id: ingredient[:recipe_id], check_box: ingredient[:check_box])
    end
    redirect_to user_path(current_user)
  end
 
  def destroy
    current_user.ingredients.where(recipe_id: 1..64).destroy_all
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def ingredient_params
    params.require(:ingredient).permit(:user_id, check_box:[], recipe_id:[] )
  end
  
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/goes_helper.rb
module GoesHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/helpers/lifes_helper.rb
module LifesHelper
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<% provide(:title, '材料') %>
<%= image_tag 'main-line.png', class: 'user-line-img' %>
<div class="container">
    <div class="row">   
        <h3 class="ingredient-p">○すべての材料と下準備</h3>
        <p>● <span class="ingredient-left">材料名</span>
            分量　
            <span class="ingredient-right"><%= image_tag 'shared-menu/star.png', class: 'star-img' %>下準備内容</span>
            <span class="ingredient-center">(分量の内訳)</span>
        </p>
        <%= form_tag ingredients_path do |f| %>
              <%= submit_tag "☆たりないものリスト☆", class: "btn btn-lg recipe-submit" %><span>今ある食材をチェックしてボタンをクリックしてね!</span></br>
            ※細切りは薄切りにした食材を3mm〜5mmほどの細さ、千切りは食材を幅1〜2mmに細く切ることです。
            <ul class="recipe-details">
                <% @recipes.each do |recipe| %>
                    <li>
                        <%= hidden_field_tag 'ingredient[][recipe_id]', recipe.id %>
                        <%= check_box_tag 'ingredient[][check_box]'  %>
                        
                        <span class="ingredient-left"><%= recipe.ingredient %></span>　
                        <% if recipe.amount.present? %><%= recipe.amount %><% end %>　
                        <% if recipe.prepare.present? %><span class="ingredient-right"><%= image_tag 'shared-menu/star.png', class: 'star-img' %><%= recipe.prepare %></span><% end %>
                        <% if recipe.breakdown.present? %><span class="ingredient-center"><%= recipe.breakdown %></span><% end %>
                    </li>
                <% end %>
            </ul>
            
        <% end %>
        <div class="to-recipe text-center">
            </br>
            <%= link_to("● レシピページへ ●", recipes_path) %>
        </div>
    </div> 
    
</div> 