config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  devise_for :users, :controllers => {
    :registrations => "registrations"
  }
  resources :users, only: [:show, :index, :destroy] do
    member do
      get :friend, :friends_list, :talk
    end
  end
  resources :posts
  resources :recipes, only: [:index]
  resources :others, only: [:index]
  resources :travels, only: [:index]
  resources :lifes, only: [:index]
  resources :learns, only: [:index]
  resources :healths, only: [:index]
  resources :cooks, only: [:index]
  resources :goes, only: [:index]
  resources :ingredients, only: [:index, :create, :destroy]
  resources :surveys, only: [:create]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :friends, only: [:create, :destroy]
  resources :talks, only: [:create, :destroy]

  

end

app/models/comment.rb
class Comment < ApplicationRecord
    
    belongs_to :user
    belongs_to :post
    
    validates :post_id, presence: true
    validates :user_id, presence: true
    validates :content, presence: true
    
end

app/models/friend.rb
class Friend < ApplicationRecord
    
    belongs_to :user, class_name: 'User', foreign_key: 'user_id'
    belongs_to :rq, class_name: 'User', foreign_key: "user_id_rq"
    
    validates :user_id, presence: true
    validates :user_id_rq, presence: true
     
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    
    belongs_to :user
    belongs_to :recipe
    
end

app/models/like.rb
class Like < ApplicationRecord
    
    belongs_to :user
    belongs_to :post
    
    validates :post_id, presence: true
    validates :user_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    
    belongs_to :user
    has_many :post_details, dependent: :destroy
    
    has_many :users, through: :likes
    has_many :likes, dependent: :delete_all
    
    has_many :users, through: :comments
    has_many :comments, dependent: :delete_all
    
    accepts_nested_attributes_for :post_details, allow_destroy: true
    default_scope -> { order('created_at DESC') }
    
    validates :user_id, presence: true
    validates :category, presence: true
    validates :title, presence: true
    validates :main_content, presence: true
    
end

app/models/post_detail.rb
class PostDetail < ApplicationRecord
    
    belongs_to :post
    default_scope -> { order('created_at ASC') }
    
    mount_uploader :image, ImageUploader
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    
    has_many :users, through: :ingredients
    has_many :ingredients
    
end

app/models/sentence.rb
class Sentence < ApplicationRecord
end

app/models/survey.rb
class Survey < ApplicationRecord
    belongs_to :user
    
    validates :user_id, presence: true
    validates :category, presence: true

end

app/models/talk.rb
class Talk < ApplicationRecord
    belongs_to :written_user, class_name: 'User', foreign_key: 'written_user_id'
    belongs_to :receiver_user, class_name: 'User', foreign_key: 'receiver_user_id'
    
    validates :written_user, presence: true
    validates :receiver_user, presence: true
    validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
    
    mount_uploader :image, ImageUploader
    
    validates :name, presence: true, length: { maximum: 50 }
    
    has_many :recipes, through: :ingredients
    has_many :ingredients, dependent: :destroy
    
    has_many :posts, through: :likes
    has_many :likes, dependent: :delete_all
    
    has_many :posts, through: :comments
    has_many :comments, dependent: :delete_all
    
    has_many :friends_of_user, class_name: 'Friend', foreign_key: 'user_id',dependent: :delete_all
    has_many :friends_of_user_id_rq, class_name: 'Friend', foreign_key: 'user_id_rq',dependent: :delete_all
    has_many :user_id, through: :friends_of_user
    has_many :user_id_rq, through: :friends_of_user_id_rq
    
    has_many :talks_of_written_user, class_name: 'Talk', foreign_key: 'written_user_id',dependent: :destroy
    has_many :talks_of_receiver_user, class_name: 'Talk', foreign_key: 'receiver_user_id',dependent: :destroy
    has_many :written_user_id, through: :talks_of_written_user
    has_many :receiver_user_id, through: :talks_of_receiver_user
    
    
    has_many :surveys, dependent: :destroy
    
    has_many :posts, dependent: :destroy
    
    scope :get_by_name, ->(name) {
    where("name like ?" , "%#{name}%")
    }
    
    def like?(post)
        likes.find_by(post_id: post.id)
    end
    
    def accept?(user)
       friends_of_user.find_by(user_id_rq: user.id) && friends_of_user_id_rq.find_by(user_id: user.id)
    end
    
    def friend_request?(user)
       friends_of_user.find_by(user_id_rq: user.id)
    end
    
    def wait?(user)
      friends_of_user_id_rq.find_by(user_id: user.id)
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: :destroy
  
  def index
    @posts = Post.paginate(page: params[:page], per_page: 15)
    @like = current_user.likes.new
  end

  def edit
    @post = Post.find(params[:id])
    # @post.post_details.image.cache! unless @post.post_details.image.blank?
  end

  def new
    @post = current_user.posts.new
    @post.post_details.build
  end

  def show
    @post = Post.find(params[:id])
    @comment = current_user.comments.new
    @like = current_user.likes.new
    @comments = @post.comments.paginate(page: params[:page], per_page: 15)
  end
  
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = "投稿できました！"
      redirect_to posts_path
    else
      render new_post_path
    end
  end
  
  def destroy
    @post.destroy
    redirect_to posts_path
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_path
    else 
      render :back
    end
  end
  
  private
  
  def post_params
    params.require(:post).permit(:category, :title, :main_content, :user_id, post_details_attributes: [:id, :post_id, :content, :image, :_destroy])
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
  
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/goes_helper.rb
module GoesHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/helpers/lifes_helper.rb
module LifesHelper
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_comment.html.erb
<li class="row comment">
    <div class="col-sm-8 break">
        ■ <%= comment.content %>
    </div>
    <div class="col-sm-4">
        <% user = User.find(comment.user_id) %>
        <% if user.image? %>
            <%= image_tag user.image.thumb.url %>
        <% else %>
            <%= image_tag 'user/user-face.png', class: 'index-user-face-img' %>
        <% end %>
        <%= user.name %>
    </div>
</li>

app/views/posts/_detail.html.erb
<li claa="post-contents">
    <% if detail.image? %>
        <%= image_tag detail.image.post.url %>
    <% else %>
        <%= image_tag 'post/photo.png', width: "50%" %>
    <% end %>
    <p class="detail-content break"><%= detail.content %></p>
</li>

app/views/posts/_post.html.erb
<li>
    <div class="row post-contents">
        <% if @posts.any? %>
            <% detail = PostDetail.find_by(post_id: post.id) %>
            <div class="col-md-3 text-center picture-content">
                <% if detail.present? %>
                    <% if detail.image.present? %>
                        <%= image_tag detail.image.post.url, class: 'post-img' %>
                    <% else %>
                        <%= image_tag 'post/photo.png', class: "photo-img" %>
                    <% end %> 
                    <% else %>
                    <%= image_tag 'post/photo.png', class: "photo-img" %>
                <% end %>
            </div>
            <div class="col-md-7 col-sm-9 post-content break">
                ■ <%= link_to post.title, post %></br></br>
                <%= post.main_content %></br></br>
                <% if post.user.image? %>
                    <%= image_tag post.user.image.thumb.url %>
                <% else %>
                    <%= image_tag 'user/user-face.png', class: 'index-user-face-img' %>
                <% end %>
                <%= link_to post.user.name, user_path(post.user) %>
                <span class="timestamp">　　　Posted <%= time_ago_in_words(post.created_at) %> ago</span>
            </div>
            <div class="col-md-2 col-sm-2 text-right like-box likes-content">
                <p class="category"><%= post.category %></p>
                <%= image_tag 'post/category.png', class: 'category-img' %>
                <p class="likes-count"><%= post.likes.count %></p>
                <% if current_user.like?(post) %>
                   <%= link_to like_path(post.id), method: :delete do %>
                        <%= image_submit_tag 'post/like.png', class: 'like-img' %>
                    <% end %>
                <% else %>
                    <%= form_for @like do |f| %>
                        <%= f.hidden_field :post_id, :value => post.id %>
                        <%= image_submit_tag 'post/unlike.png', class: 'like-img' %>
                    <% end %>
                <% end %>
            </div>
        <% end %>
    </div>
</li>

app/views/posts/edit.html.erb
<% provide(:title, '投稿編集') %>
<%= image_tag 'user/user-line.png', class: 'user-line-img' %>
<div class="container">
  <h2 class="j-title">投稿編集</h2>
  <div class="post-new">
    <%= nested_form_for(@post) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="field">
        <%= f.label :category %><br />
        <%= f.select :category, ["がくしゅう","けんこう","りょうり","おでかけ","くらし","りょこう","etc..."], :selected => @post.category, :class => 'category' %>
      </div>
      <div class="field break">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </div>
      <div class="field break">
        <%= f.label :main_content %><br />
        <%= f.text_area :main_content %>
      </div>
      <p>●投稿詳細：</p>
      <%= f.fields_for :post_details do |m| %>
        <div class="field">
          <%= f.label :image, "画像" %><br />
          <%= m.file_field :image %>
          <%= m.hidden_field :image_cache %>
        </div>
        <div class="field ">
          <%= f.label :content %><br />
          <%= m.text_area :content %>
        </div>
        <div class="field to-remove">
          <%=m.link_to_remove 'Delete' %>
        </div>
      <% end %>  
      <div class="field add">
        <%= f.link_to_add '追加', :post_details , class: "to-add"%>
      </div>
      <div class="field post-submit">
        <%= f.submit "編　集", class: "btn btn-lg submit" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, '投稿index') %>
<%= image_tag 'user/user-line.png', class: 'user-line-img' %>
<div class="container">
    
    <div class="post-sample">
    <p class="title">Example</p>
        <div class="row post-contents">
            <div class="col-md-3 text-center picture-content">
               <%= image_tag 'post/index-sample.png', class: 'index-sample-img' %><span>投稿写真</span>
            </div>
            <div class="col-md-4 col-sm-5 post-content">
                <p>●投稿タイトル</p>
                <p>投稿内容のまとめ</br>☆詳しい内容はクリックしてね！</p>
                </br>
                <p><%= image_tag 'post/sample-user.png', class: 'sample-user-img' %>投稿者さん </p>
            </div>
            <div class="col-md-3 col-sm-5 likes-content-comment text-right">
                <p class="text-left likes-info">クリックしてお気に入りに登録するとピンク色になるよー</br>
                数字はみんながお気に入りをした数だよ‼︎</p>
                </br>
            </div>
            <div class="col-md-2 col-sm-2 text-right like-box likes-content">
                <p class="category">カテゴリー</p>
                <%= image_tag 'post/category.png', class: 'category-img' %>
                <p class="likes-count">10</p>
                <%= image_submit_tag 'post/like.png', class: 'like-img' %>
            </div>
        </div> 
    </div>
    <p class="j-title">投稿一覧</p>
    <ul class="post-index">
            <%= render @posts %>
    </ul>
    <%= will_paginate renderer: BootstrapPagination::Rails %>
        
        
    </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, '新規投稿') %>
<%= image_tag 'user/user-line.png', class: 'user-line-img' %>
<div class="container">
  <h2 class="j-title">新規投稿</h2>
  <div class="post-new">
    <%= nested_form_for(@post) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.label :category %><br />
        <%= f.select :category, ["がくしゅう","けんこう","りょうり","おでかけ","くらし","りょこう","etc..."], :prompt => "選んでね！", :class => 'category' %>
      </div> 
      <div class="field break">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </div>
      <div class="field break">
        <%= f.label :main_content %><br />
        <%= f.text_area :main_content %>
      </div>
      <p>●投稿詳細：</p>
      <%= f.fields_for :post_details do |m| %>
        <div class="field">
          <%= f.label :image %><br />
          <%= m.file_field :image %>
        </div>
        <div class="field break">
          <%= f.label :content %><br />
          <%= m.text_area :content %>
        </div>
        <div class="field to-remove">
          <%=m.link_to_remove 'Delete' %>
        </div>
      <% end %>  
      <div class="field add">
        <%= f.link_to_add '追加', :post_details , class: "to-add"%>
      </div>
      <div class="field post-submit">
        <%= f.submit "投 稿", class: "btn btn-lg submit" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<%= image_tag 'user/user-line.png', class: 'user-line-img' %>
<div class="container">
    <div class="row">
        <div class="col-sm-3  post-show-top">
            <% if @post.user.image? %>
                <%= image_tag @post.user.image.thumb.url %>
            <% else %>
                <%= image_tag 'user/user-face.png', class: 'index-user-face-img' %>
            <% end %>
            <%= link_to @post.user.name, user_path(@post.user) %>
            <p class="timestamp">Posted <%= time_ago_in_words(@post.created_at) %> ago</p>
        </div>
        <% if current_user == @post.user %>
            <div class="col-sm-2 post-edit">                        
                <%= link_to "edit", edit_post_path %>
            </div>
            <div class="col-sm-2 col-sm-offset-1 post-delete">
                <%= link_to "delete",@post, method: :delete, data: { confirm: "You sure?" }, title: @post.title %>
            </div>
        <% end %>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <p class="j-title break"><%= @post.title %></p>
            <p class="main-content break"><%= @post.main_content %></p>
        </div>
        <div class="col-sm-2 text-right like-box likes-content">
            <p class="category"><%= @post.category %></p>
            <%= image_tag 'post/category.png', class: 'category-img' %>
            <p class="likes-count"><%= @post.likes.count %></p>
            <% if current_user.like?(@post) %>
               <%= link_to like_path, method: :delete do %>
                    <%= image_submit_tag 'post/like.png', class: 'like-img' %>
                <% end %>
            <% else %>
                <%= form_for @like do |f| %>
                <%= f.hidden_field :post_id, :value => @post.id %>
                    <%= image_submit_tag 'post/unlike.png', class: 'like-img' %>
                <% end %>
            <% end %>
        </div>
    </div>

    <% if @post.post_details.any? %>
        <% @details = @post.post_details %>
        <ul>
            <%= render partial: 'posts/detail', collection: @details %>
        </ul>
    <% end %>

    <p class="post-comment">COMMENT <%= image_tag 'post/comment.png', class: 'show-like-img' %></p>
    
    <% if @comments.any? %>
        <ul>
            <%= render partial: 'posts/comment', collection: @comments %>
        </ul>
    <% end %>
    
    
    <%= form_for @comment do |f| %>
    <%= f.hidden_field :post_id, :value => @post.id %>
    <div class="row">
        <div class="field text-center">
          <%= f.text_area :content, placeholder: "コメントする", class: "comment-field" %>
        </div>
              <%= f.submit "送信", class: "btn btn-lg comment-submit" %>
    </div>
  <% end %>
</div>